* Caution
  Configurations are mostly depend on taste. You may not like all the
  provided settings here. Probably the best thing to do is copy bits
  and pieces from different individual files named by the
  packages/context.

* Dependencies.
I use mostly latest version of Emacs. In fact to I build and use emacs from
bzr trunk and keep stable versions around for fail safe and testing purposes.

So if you want to use all of these settings you might want to look for
these before you get going to use.

- GNU Emacs latest version, (above 24.0 is recommondad)
- elpa (included in Emacs 24.0)
- git (cloning most of the packages by [[https://github.com/dimitri/el-get][el-get]] (package manager))

** Building Emacs from bzr/git HEAD
see also my other [[http::/github.com/yyr/build-emacs][script]] which I use to build emacs automatically.

To build emacs on ubuntu (I follow bzr/git HEAD) I needed the
following OS packages.
  - build-essantial
  - build-dep emacs23
  - autoconf

    #+BEGIN_SRC sh
sudo apt-get build-essentials
sudo apt-get build-dep emacs23
./configure --prefix="/home/username/local/emacs-git" #install directory ~/local/emacs-git
make bootstrap
make install
    #+END_SRC

* Use
  - download through git or a [[https://github.com/yyr/emacsd/zipball/master][zip file]]
  - rename the folder .emacs.d in the home
  - (optionally) comment out lines are needed for you in "init.el".
  - fire up a Emacs
    el-get should start installing your additional external packages

* License.
GPL v3 or later.

* references
see the cite file
