* Dependencies to look for to use these configuration
you might want to look for these before you get going to use.

* Dependencies
emacs "24.0.50.1"
elpa	        - elpa is included in emacs 24.0
el-get  	- https://github.com/dimitri/el-get 
autoconf 	- emacs-w3m
git		- for cloning most of the packages by el-get

to build emacs on ubuntu (I follow bzr/git HEAD) I needed following.
build-essantials
build-dep emacs23

* Building emacs from bzr/git HEAD
./configure --prefix="/home/username/local/emacs-git" #install directory ~/local/emacs-git
sudo apt-get build-essentials
sudo apt-get build-dep emacs23
make bootstrap 
make install

* change the el-get-sources
  This configuration depend on el-get to maintain/install many emacs
  plugins. one need to change el-get-sources which packages they want
  to have.

* CREDITS:
I copied shamelessly from so many places on the internet.  I am believing that as emacs the configurations also must go GPLd.
here I write, some of the places I collected.

emacswiki.org	   - this is where it started and continues
alex schroeder 	   - http://www.emacswiki.org/alex/
Steve Purcell  	   - git.sanityinc.com (many thanks to him)
Alex Ott           - alexott.com <alexott@Agmail.com>
Andy Stewart	   - http://www.emacswiki.org/emacs-en/AndyStewart
