* Caution
  Configurations are mostly depend on taste. You may not like all the
  provided settings here. Probably the best thing to do is copy bits
  and pieces from different individual files named by the
  packages/context.

* Dependencies.
  if you want to use all of these settings you might want to look for
  these before you get going to use.

  - GNU Emacs 23.3
  - elpa (included in Emacs 24.0)
  - git (cloning most of the packages by [[https://github.com/dimitri/el-get][el-get]] (package manager))
  - CVS (optional which is needed emacs-w3m by el-get I guess)

** Building Emacs from bzr/git HEAD
   To build emacs on ubuntu (I follow bzr/git HEAD) I needed the
   following OS packages.
  - build-essantial
  - build-dep emacs23
  - autoconf

    #+BEGIN_SRC sh
sudo apt-get build-essentials
sudo apt-get build-dep emacs23
./configure --prefix="/home/username/local/emacs-git" #install directory ~/local/emacs-git
make bootstrap
make install
    #+END_SRC

* Use
  - download through git or a [[https://github.com/yyr/emacsd/zipball/master][zip file]]
  - rename the folder .emacs.d in the home
  - (optionally) comment out lines are needed for you in "init.el".
  - fire up a Emacs
    el-get should start installing your additional external packages

* License.
  GPL v3 or later.

* references
  see the cite file
