
* Caution
  configurations are mostly depends on taste. You may not
  like/suitable all the provided settings here. Probably best thing to
  do is copy bits and pieces from organized(?) individual files.

* Dependencies.
  if you want to use all of these settings you might want to look for
  these before you get going to use.

** Dependencies
  - emacs 23.3
  - elpa          - elpa is included in emacs 24.0
  - el-get        - https://github.com/dimitri/el-get
  - autoconf      - emacs-w3m
  - git           - for cloning most of the packages by el-get

** Building emacs from bzr/git HEAD
   to build emacs on ubuntu (I follow bzr/git HEAD) I needed following.
  - build-essantial
  - build-dep emacs23

   #+BEGIN_SRC sh
sudo apt-get build-essentials
sudo apt-get build-dep emacs23
./configure --prefix="/home/username/local/emacs-git" #install directory ~/local/emacs-git
make bootstrap
make install
   #+END_SRC

* use
  - download through git or a [[https://github.com/yyr/emacsd/zipball/master][zip file]]
  - rename the folder .emacs.d in the home
  - change the el-get-sources in init-el-get.el
    This configuration depend on el-get to maintain/install many emacs
    plugins. one need to change el-get-sources which packages they want
    to have.
  - may comment out few lines in init.el
  - fire up a emacs
    el-get should start installing your plugins

* License.
  GPL v3 or later.

* references
  see the cite file
