; Copyright (C) Yagnesh Raghava Yakkala. http://yagnesh.org
;    File: (>>FILE<<)
;  Author: Yagnesh Raghava Yakkala <yagnesh@live.com>
; Created: (>>DATE<<)
; Licence: GPL v3 or later. You should get a copy from <http://www.gnu.org/licenses/gpl.html>

; Description:
;

load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_code.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/csm/gsn_csm.ncl"
load "$NCARG_ROOT/lib/ncarg/nclscripts/wrf/WRFUserARW.ncl"

begin


end
